<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '23e23a0e32881919f0f8229f00c988b8',
  'DATABASE_URL' => 'mysql://root:vuanh123@127.0.0.1:3306/htest1',
);
